#!/bin/bash

## Show what commands are being run
set -o xtrace

username=nicme26
host=remote.ida.liu.se
dir=/home/nicme26/www-pub/pelib
target=$username@$host:$dir

echo Copying files to server. Append $HOME/.ssh/id_rsa.pub to $username@$host:'$'HOME/.ssh/authorized_keys to avoid password prompts. Use ssh-keygen to generate $HOME/.ssh/id_rsa.pub if it doesn\'t exist.

## Generate an archive
make dist
scp `ls *.tar.gz|sort -V|head -1` $target/download/

## Generate documentation and copy it in output directory
make doc
echo '<!--#set var='\"dir\" value=\"$dir\"'-->' | tee -a doc/$package-data.shtml
scp -r doc/* $target

